version: '3.2'
services:  
  integrated_db:
  # The database that holds all the integrated data and maybe some other nice to have's like:
  #   - World Port Index'
  #   - World EEZ shapefile
  # The schema is also set up in the start up scripts. You must add the scripts you want into the script dir
  # to build those schemas. 
  # https://hub.docker.com/r/timescale/timescaledb-postgis/tags
    container_name: ${PROJECT_NAME}_db
    hostname: ${DB_HOST}
    # image: timescale/timescaledb-postgis:${TIMESCALE_TAG}
    # Above image used old 2.x version of postgis. Below image uses postgis 3.1
    # image: timescale/timescaledb-ha:${TIMESCALE_TAG}
    # Dockerfile below has wget and shp2pgsql installed on it
    build: ./build/db/.
    shm_size: 12g
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - ${DB_EXT_PORT}:${DB_INT_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_UID=${UID}
      - POSTGRES_GID=${GID}
    volumes:
## Volume commented out to test building of DB. Uncomment for DB persisitance
#      - ./volumes/db/:/var/lib/postgresql/data
      - ./build/db/scripts_to_run:/docker-entrypoint-initdb.d/ 
      - ./build/db/db_init_data/:/tmp

    restart: unless-stopped
    networks:
      - db_net
    logging:
      driver: json-file
      options:
        max-size: 10m
 
networks:
    db_net:
